@echo off
echo Installing crispy-bootstrap4...
pip install crispy-bootstrap4

echo Updating requirements.txt...
pip freeze > requirements.txt

echo Making migrations...
python manage.py makemigrations

echo Applying migrations...
python manage.py migrate

echo Starting Django development server...
python manage.py runserver
