# Generated by Django 4.2.13 on 2024-07-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Citizen_back',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Citizen_front',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='static/pfps'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.ImageField(blank=True, null=True, upload_to='static/Resumes'),
        ),
    ]
