# Generated by Django 4.2.13 on 2024-07-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_userprofile_citizen_back_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
