# Generated by Django 5.0.6 on 2024-07-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chef_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/room-pictures'),
        ),
        migrations.AlterField(
            model_name='chef',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
